import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  cardWrapper: {
    position: 'relative',
    marginBottom: 16,
  },
  skeleton: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  container: {
    position: 'relative',
    borderRadius: 24,
  },
  favourite: {
    backgroundColor: '#ffffff',
    position: 'absolute',
    width: 32,
    height: 32,
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    top: 12,
    right: 12,
    borderColor: '#ffffff',
    borderWidth: 1,
    borderRadius: 32,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  favouriteIcon: {
    width: 18,
    height: 18,
  },
  gradientBox: {
    height: 150,
    borderRadius: 24,
    paddingBottom: 24,
  },
  image: {
    width: 100,
    height: 100,
    position: 'absolute',
    top: 30,
    right: 50,
  },
  types: {
    flex: 1,
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
    flexDirection: 'row',
    marginTop: 8,
    position: 'absolute',
    left: 20,
    bottom: 20,
  },
  typeImage: {
    width: 24,
    height: 24,
    marginRight: 8,
  },
  nameWrapper: {
    position: 'absolute',
    top: 20,
    left: 20,
  },
  name: {},
  shadow: {
    marginTop: 0,
    height: 5,
    width: '70%',
    top: -5,
    left: '50%',
    marginLeft: '-35%',
    zIndex: -1,
    backgroundColor: '#ffffff',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
});
