import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  cardWrapper: {
    marginBottom: 24,
    position: 'relative',
  },
  skeleton: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  container: {
    position: 'relative',
    paddingBottom: 16,
    backgroundColor: '#ffffff',
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
  },
  favourite: {
    backgroundColor: '#ffffff',
    position: 'absolute',
    width: 32,
    height: 32,
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    top: 12,
    right: 12,
    borderColor: '#ffffff',
    borderWidth: 1,
    borderRadius: 32,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  favouriteIcon: {
    width: 18,
    height: 18,
  },
  gradientBox: {
    height: 200,
    borderRadius: 24,
    paddingBottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    width: 120,
    height: 120,
  },
  types: {
    height: 48,
    marginTop: -32,
    alignItems: 'center',
    marginBottom: 10,
  },
  typesContainer: {
    position: 'relative',
    width: '50%',
    flexDirection: 'row',
  },
  type: {
    height: 48,
    flex: 1,
    backgroundColor: '#ffffff',
    borderTopRightRadius: 24,
    borderTopLeftRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeImage: {
    width: 32,
    height: 32,
    marginHorizontal: 3,
  },
  name: {
    alignItems: 'center',
  },
  shadow: {
    marginTop: 0,
    height: 5,
    width: '70%',
    top: -5,
    left: '50%',
    marginLeft: '-35%',
    zIndex: -1,
    backgroundColor: '#ffffff',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
});
